services:
  - type: web
    name: gpt-telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: 
        sync: false
      - key: 
        sync: false
